ALTER TABLE pay_periods ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'open';
ALTER TABLE pay_periods ADD COLUMN IF NOT EXISTS week_start TEXT;
ALTER TABLE pay_periods ADD COLUMN IF NOT EXISTS week_end TEXT;
ALTER TABLE pay_periods ADD COLUMN IF NOT EXISTS paid_at TEXT;
ALTER TABLE pay_periods ADD COLUMN IF NOT EXISTS created_at TEXT;
